denuncieaqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('mapa/', views.mapa, name="mapa"),
    path('redirecionamento/', views.redirecionamento, name="redirecionamento"),
    path('duvidas/', views.duvidas, name="duvidas"),
    path("admin/", admin.site.urls),
    path("usuarios/", include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    # path('inicio/', views.cadastro, name="inicio"),
    path('cadastro/', views.cadastro, name="cadastro"),
    path('login/', views.login_view, name="login"),
    path('denuncia/', views.denuncia, name="denuncia"),
    path('historico/', views.historico, name="historico"),
    path('sair/', views.sair, name="sair")
]

usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    cpf = models.CharField(max_length=11, unique=True)

class Denuncia(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='denuncias')
    tipo_denuncia = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to='denuncias/')
    descricao = models.TextField()
    local_denuncia = models.CharField(max_length=500)

    def __str__(self):
        return f'Denúncia de {self.user.username} - {self.tipo_denuncia}'

denuncieaqui/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from usuarios.models import CustomUser

def inicio(request):
    if request.method == "GET":
        return render(request, 'inicio.html')

def mapa(request):
    if request.method == "GET":
        return render(request, 'mapa.html')

def redirecionamento(request):
    if request.method == "GET":
        return render(request, 'redirecionamento.html')
    
def duvidas(request):
    if request.method == "GET":
        return render(request, 'duvidas.html')

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import CustomUser, Denuncia
from django.contrib import auth
import re

def is_valid_cpf(cpf):
    cpf = re.sub(r'[^0-9]', '', cpf)

    cpf_repetido = cpf == cpf[0] * len(cpf)
    if cpf_repetido:
        return False

    multiplicador = 10
    soma_total = 0
    for numero in cpf[:9]:
        soma_total += int(numero) * multiplicador
        multiplicador -= 1

    primeiro_numero = (soma_total * 10) % 11
    primeiro_numero = primeiro_numero if primeiro_numero <= 9 else 0

    # Verificar o segundo dígito do CPF
    multiplicador = 11
    soma_total = 0
    for numero in cpf[:10]:
        soma_total += int(numero) * multiplicador
        multiplicador -= 1

    segundo_numero = (soma_total * 10) % 11
    segundo_numero = segundo_numero if segundo_numero <= 9 else 0

    cpf_temp = cpf[:9] + str(primeiro_numero) + str(segundo_numero)

    return cpf_temp == cpf


def generate_username(email):
    username = email
    return username

    
def cadastro(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('inicio')
        return render(request, 'cadastro.html')
    
    elif request.method == "POST":
        nome = request.POST.get('nome')
        sobrenome = request.POST.get('sobrenome')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        confirmar_senha = request.POST.get('confirmar_senha')
        cpf = request.POST.get('cpf')

        if not is_valid_cpf(cpf):
            messages.error(request, 'CPF inválido.')
            return redirect('/usuarios/cadastro')

        if not (nome and sobrenome and email and senha and confirmar_senha and cpf):
            messages.error(request, 'Por favor, preencha todos os campos.')
            return redirect('/usuarios/cadastro')

        if senha != confirmar_senha:
            messages.error(request, 'As senhas não coincidem.')
            return redirect('/usuarios/cadastro')

        if len(senha) < 6:
            messages.error(request, 'A senha deve ter pelo menos 6 caracteres.')
            return redirect('/usuarios/cadastro')

        if CustomUser.objects.filter(cpf=cpf).exists():
            messages.error(request, 'Este CPF já está cadastrado.')
            return redirect('/usuarios/cadastro')
        
        if CustomUser.objects.filter(email=email).exists():
            messages.error(request, 'Este E-mail já está cadastrado.')
            return redirect('/usuarios/cadastro')

        username = generate_username(email)

        usuario = CustomUser.objects.create_user(
            username=username,
            first_name=nome,  
            last_name=sobrenome,
            email=email,
            password=senha,
            cpf=cpf
        )

        usuario.save()

        messages.success(request, 'Cadastro realizado com sucesso. Faça o login.')
        return redirect('usuarios:login')


def login_view(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('inicio')
        return render(request, 'login.html')
    
    elif request.method == "POST":
        email = request.POST.get('email')
        senha = request.POST.get('senha')

        user = auth.authenticate(request, username=email, password=senha)
        print(request.user)
        print(senha)
        if user:
            auth.login(request, user)
            print(request.user)
            return redirect('/')
        
        messages.error(request, 'E-mail ou senha inválidos')
        return redirect('usuarios:login')
    

def denuncia(request):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect('redirecionamento')  
        return render(request, 'denuncia.html')
    
    elif request.method == 'POST':
        tipo_denuncia = request.POST.get('tipo_denuncia')
        descricao = request.POST.get('descricao')
        localizacao = request.POST.get('local_denuncia')
        
        # Processar a imagem, se necessário
        imagem = request.FILES.get('imagem_denuncia')

        # Salvar os dados no banco de dados
        # Supondo que o usuário esteja autenticado e você tenha acesso a ele através de request.user
        denuncia = Denuncia.objects.create(
            user=request.user,
            tipo_denuncia=tipo_denuncia,
            imagem=imagem,
            descricao=descricao,
            local_denuncia=localizacao
        )

        # Redirecionar para alguma página de confirmação
        messages.success(request, 'Denúncia realizada com sucesso. Aguarde a validação.')
        return redirect('/usuarios/denuncia')


def historico(request):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect('redirecionamento')
    
    denuncias = Denuncia.objects.filter(user=request.user)

    return render(request, 'historico.html', {'denuncias': denuncias})


def sair(request):
    if not request.user.is_authenticated:
            return redirect('inicio')  
    
    auth.logout(request)

    return redirect('/usuarios/login')


 

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'geral/css/base.css' %}">
    <title>{% block 'title' %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block 'head' %}{% endblock 'head' %}
  </head>
  <body>
    {% block 'body' %}{% endblock 'body' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/redirecionamento.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'geral/css/redirecionamento.css' %}">
</head>
<body>
    <div class="container">
        <div class="box">
            <h1 class="title">Calma lá!</h1>
            <p class="text">Antes de poder utilizar de nossa plataforma, por favor, <strong>Realize o seu Cadastro.</strong> Caso já possua uma conta, por favor, <strong>Conecte-se</strong> e usufrua de todas as abas que desejar!</p>
            <div class="button-container">
                <a href="{% url 'usuarios:cadastro' %}" class="button1"><h1><strong>Cadastre-se</h1></strong></a>
                <a href="{% url 'usuarios:login' %}" class="button2"><h1><strong>Entre</h1></strong></a>
            </div>
        </div>
        <div class="box image-box">
        </div>
    </div>
</body>
</html>

usuarios/templates/cadastro.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'usuarios/css/cadastro.css' %}">
{% endblock 'head' %}
{% block 'body' %}

<div id="img"></div>
<div class="cadastro-container">
    <div>
        <div class="header">
            <div id="logo"></div>
            <span id="titulo"><span class="denuncie">DENUNCIE</span><span class="aqui">AQUI</span></span>
        </div>
    </div>
    <form action="{% url 'usuarios:cadastro' %}" method="POST">
        {% csrf_token %}
                        
        <h2 class="fonte-destaque1"></h2>
        <br>
        
        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <section class="alert alert-danger">
                    {{ message }}
                </section>
            {% else %}
                <section class="alert alert-success">
                    {{ message }}
                </section>
            {% endif %}
        {% endfor %}
    {% endif %}

        
        <div class="row">
            <div class="col-md">
                <label for="id_nome">Nome</label>
                <input type="text" name="nome" id="id_nome" class="form-control" placeholder="Seu nome" required>
            </div>
            <div class="col-md">
                <label for="id_sobrenome">Sobrenome</label>
                <input type="text" name="sobrenome" id="id_sobrenome" class="form-control" placeholder="Seu sobrenome" required>
            </div>
        </div>
        <br>
        <label for="id_email">E-mail</label>
        <input type="email" name="email" id="id_email" placeholder="example@email.com" class="form-control" required>
        <br>
        <label for="id_cpf">CPF</label>
        <input type="text" name="cpf" id="id_cpf" class="form-control" placeholder="000.000.000-00" pattern="\d{3}\.\d{3}\.\d{3}-\d{2}" required>
        <br>
        <div class="row">
            <div class="col-md">
                <label for="id_senha">Senha</label>
                <input type="password" name="senha" id="id_senha" class="form-control" placeholder="Digite sua senha ..." minlength="6" required>
            </div>
            <div class="col-md">
                <label for="id_confirmar_senha">Confirmar senha</label>
                <input type="password" name="confirmar_senha" id="id_confirmar_senha" class="form-control" placeholder="Digite sua senha novamente ..." minlength="6" required>
            </div>
        </div>
        <br>
    
        <input type="submit" value="Cadastrar" class="btn btn-success btn-dark-color" id="id_submit">
        <a href="{% url 'usuarios:login' %}" class="btn btn-dark-color-outline" style="border: 1px #000;">Já possuo uma conta</a>

    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>



{% endblock 'body' %}

usuarios/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'usuarios/css/login.css' %}">
{% endblock 'head' %}

{% block 'body' %}


<div class="main" style="position: ;">
    <form action="{% url 'usuarios:login' %}" method="POST">
                <div class="header" style="">
                    <div id="logo"></div>
                    <span id="titulo"><span class="denuncie">DENUNCIE</span><span class="aqui">AQUI</span></span>
                </div> <br>
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                    <section class="alert alert-danger">
                                        {{ message }}
                                    </section>
                                {% else %}
                                    <section class="alert alert-success">
                                        {{ message }}
                                    </section>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                

                    {% csrf_token %}
                <input id="email" type="text" placeholder="E-mail" name="email">
                <input id="senha" type="password" placeholder="Senha" name="senha">
                <br>
                <div class="button-group">
                    <input class="botao-entrar" type="submit" value="Entrar">
                    <a class="botao-criar" href='{% url 'usuarios:cadastro' %}'>Criar conta</a>

                </div>
    </form>
</div>


{% endblock 'body' %}